# This is a basic workflow to help you get started with Actions

name: fire repository_dispatch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  repository_dispatch:
    types: [generate-sdk]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check client_payload
        if: ${{ ! github.event.client_payload.origin_ref }}
        run: exit 1

      - name: Show parameters
        run: |
          echo "${{ toJson(github.event) }}"
    
      - name: Show parameters (client_payload)
        run: |
          echo "${{ toJson(github.event.client_payload) }}"

      - uses: actions/github-script@v2
        if: ${{ contains(github.event.client_payload.origin_ref, 'refs/tags/') }}
        id: release_tag
        with:
          result-encoding: string
          script: |
            const { origin_ref } = context.payload.client_payload
            const words = origin_ref.split('/')
            return words[2]

      - name: Show returned value
        env:
          RELEASE_TAG_CONTEXT: ${{ toJson(steps.release_tag.outputs) }}
        run: echo "$RELEASE_TAG_CONTEXT"

      - name: schema url
        env:
          SCHEMA_URL: https://raw.githubusercontent.com/freee/freee-api-schema/${{ steps.release_tag.outputs.result }}/v2020_06_15/open-api-3/api-schema.yml
        run: echo "$SCHEMA_URL"

      - name: Show url again
        run: echo "${{ steps.release_tag.outputs.result }}"
