# This is a basic workflow to help you get started with Actions

name: fire repository_dispatch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  repository_dispatch:
    types: [generate-sdk]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check client_payload
        if: ${{ ! github.event.client_payload.origin_ref }}
        run: exit 1

      - uses: actions/github-script@v2
        if: contains(github.event.client_payload.origin_ref, 'refs/tags/')
        id: release_tag
        with:
          script: |
            const words = github.event.client_payload.origin_ref.split('/')
            return words[2]

      - name: schema url
        env:
#           key: https://github.com/freee/freee-api-schema/blob/v0.0.14/v2020_06_15/open-api-3/api-schema.yml
          SCHEMA_URL: https://github.com/freee/freee-api-schema/blob/${{ steps.release_tag.outputs }}/v2020_06_15/open-api-3/api-schema.yml
        run: env "$SCHEMA_URL"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Show parameters
        run: |
          echo "${{ toJson(github.event) }}"
